# Generated by Django 5.2.9 on 2025-12-14 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Talent/Portfolio', 'verbose_name_plural': 'Talents/Portfolio'},
        ),
        migrations.AddField(
            model_name='talent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='gambar',
            field=models.ImageField(blank=True, help_text='Screenshot/gambar project', null=True, upload_to='talents/'),
        ),
        migrations.AddField(
            model_name='talent',
            name='kategori',
            field=models.CharField(blank=True, help_text='Contoh: Project, Internship, Competition, etc', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='tanggal_selesai',
            field=models.DateField(blank=True, help_text='Kosongkan jika masih berlangsung', null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='deskripsi',
            field=models.TextField(help_text='Deskripsi detail'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='judul',
            field=models.CharField(help_text='Judul project/pengalaman', max_length=200),
        ),
        migrations.AlterField(
            model_name='talent',
            name='link_portfolio',
            field=models.URLField(blank=True, help_text='Link ke portfolio/demo', null=True),
        ),
    ]
