# Generated by Django 5.2.9 on 2025-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_alter_mahasiswa_options_mahasiswa_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.CharField(blank=True, default='', help_text='Tahun angkatan', max_length=10),
            preserve_default=False,
        ),
    ]
