# Generated by Django 5.2.9 on 2025-12-14 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_pengalaman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session identifier for anonymous users', max_length=255, null=True)),
                ('viewed_by_ip', models.GenericIPAddressField(blank=True, help_text='IP address of viewer', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('referrer', models.URLField(blank=True, help_text='Referring URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='mahasiswa.mahasiswa')),
                ('viewed_by_user', models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile View',
                'verbose_name_plural': 'Profile Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mahasiswa_p_created_592788_idx'), models.Index(fields=['mahasiswa', '-created_at'], name='mahasiswa_p_mahasis_22cbf2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('viewed_by_user__isnull', False)), fields=('mahasiswa', 'viewed_by_user'), name='unique_user_profile_view'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('mahasiswa', 'session_key'), name='unique_session_profile_view')],
            },
        ),
    ]
