# Generated by Django 5.2.9 on 2025-12-09 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('prodi', models.CharField(max_length=100)),
                ('fakultas', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profil/')),
                ('bio', models.TextField(blank=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
