# Generated by Django 5.2.9 on 2025-12-14 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahasiswa', 'verbose_name_plural': 'Mahasiswa'},
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.CharField(blank=True, help_text='Tahun angkatan', max_length=10),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='telepon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Jumlah profile views'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='website',
            field=models.URLField(blank=True, help_text='Personal website/portfolio', null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='bio',
            field=models.TextField(blank=True, help_text='Deskripsi singkat tentang diri'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Profil aktif/nonaktif'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mahasiswa',
            index=models.Index(fields=['-created_at'], name='mahasiswa_m_created_7e83fd_idx'),
        ),
        migrations.AddIndex(
            model_name='mahasiswa',
            index=models.Index(fields=['prodi'], name='mahasiswa_m_prodi_b85467_idx'),
        ),
        migrations.AddIndex(
            model_name='mahasiswa',
            index=models.Index(fields=['is_active'], name='mahasiswa_m_is_acti_46dd69_idx'),
        ),
    ]
