# Generated by Django 5.2.9 on 2025-12-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_add_angkatan_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengalaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(help_text='Posisi/jabatan', max_length=200)),
                ('organisasi', models.CharField(help_text='Nama perusahaan/organisasi', max_length=200)),
                ('tahun_mulai', models.CharField(help_text='Tahun mulai', max_length=10)),
                ('tahun_selesai', models.CharField(blank=True, help_text='Tahun selesai (kosong jika masih berlangsung)', max_length=10)),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi pengalaman')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengalaman', to='mahasiswa.mahasiswa')),
            ],
            options={
                'verbose_name': 'Pengalaman',
                'verbose_name_plural': 'Pengalaman',
                'ordering': ['-tahun_mulai'],
            },
        ),
    ]
