# Generated by Django 5.2.9 on 2025-12-14 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_endorsements_given', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Skill Endorsement',
                'verbose_name_plural': 'Skill Endorsements',
                'ordering': ['-created_at'],
                'unique_together': {('skill', 'endorsed_by')},
            },
        ),
    ]
